esphome:
  friendly_name: ${node_friendly_name}
  name: ${node_name}
  build_path: ../../build/${node_name}

preferences:
  flash_write_interval: 2min

ethernet:
  type: IP101
  mdc_pin: 23
  mdio_pin: 18
  clk_mode: GPIO0_IN
  power_pin: 5
  phy_addr: 1

# captive_portal:

# improv_serial:

# Enable logging
logger:

# Enable Home Assistant API and define services
api:
  encryption:
    key: !secret api_key
  reboot_timeout: 120min

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic
  - platform: factory_reset
    name: Wipe Preferences
    entity_category: diagnostic
