esphome:
  friendly_name: ${node_friendly_name}
  name: ${node_name}
  build_path: ../../build/${node_name}

preferences:
  flash_write_interval: 2min

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_password
  reboot_timeout: 120min
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${node_name}
    password: !secret ap_password

# captive_portal:

improv_serial:

# Enable logging
logger:

# Enable Home Assistant API and define services
api:
  encryption:
    key: !secret api_key
  reboot_timeout: 120min

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic
  - platform: factory_reset
    name: Wipe Preferences
    entity_category: diagnostic

sensor:
  - platform: wifi_signal
    name: Wi-Fi Signal
    update_interval: 15s
