substitutions:
  node_name: esp-snowflake-controller
  node_friendly_name: Snowflake
  project_name: Snowflake_Controller
  project_version: v1

packages:
  esp_common: !include shared/esp__common_core.yaml

wifi:
  enable_btm: true
  enable_rrm: true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

logger:
  hardware_uart: UART0

globals:
  # makes sure we don't switch the snowflakes' state if it's already in the desired state
  - id: snowflake_state
    type: bool
    initial_value: "false"

status_led:
  pin:
    number: 2
    inverted: true

switch:
  - platform: gpio
    id: snowflake_button
    name: Button
    pin: 9
  - platform: gpio
    id: snowflake_power_enable
    name: Power Enable
    restore_mode: RESTORE_DEFAULT_OFF
    pin: 21
  - platform: template
    id: snowflake_power
    name: Power
    lambda: "return id(snowflake_state);"
    turn_off_action:
      - if:
          condition:
            lambda: "return id(snowflake_state);"
          then:
            - globals.set:
                id: snowflake_state
                value: "false"
            - switch.turn_on: snowflake_button
            - delay: 2250ms
            - switch.turn_off: snowflake_button
    turn_on_action:
      - if:
          condition:
            lambda: "return !id(snowflake_state);"
          then:
            - globals.set:
                id: snowflake_state
                value: "true"
            - switch.turn_on: snowflake_button
            - delay: 500ms
            - switch.turn_off: snowflake_button
  - platform: template
    id: snowflake_button_short_press
    name: Button Short Press
    turn_on_action:
      - switch.turn_on: snowflake_button
      - delay: 500ms
      - switch.turn_off: snowflake_button
  - platform: template
    id: snowflake_button_long_press
    name: Button Long Press
    turn_on_action:
      - switch.turn_on: snowflake_button
      - delay: 2250ms
      - switch.turn_off: snowflake_button

binary_sensor:
  - platform: gpio
    id: snowflake_button_input
    name: Button Input
    pin: 20
    on_click:
      - switch.toggle: snowflake_power
