substitutions:
  node_name: esp-lights-string-fence-north
  node_friendly_name: String Lights Fence North

packages:
  esp_common: !include shared/esp__common_core.yaml
  esp_lights_string_base: !include shared/esp-lights-string-base.yaml
