substitutions:
  node_name: esp-lights-front-room-column-ne
  node_friendly_name: "Front Room Northeast Column Lamp"

packages:
  esp_common: !include shared/esp__common_core.yaml

esp32:
  board: esp32dev

status_led:
  pin:
    number: 5
    inverted: true

remote_receiver:
  id: ir_rx
  dump: nec
  pin:
    inverted: true
    number: 36
  on_nec:
    then:
      lambda: |-
        if (x.command == 0xBF40) {
          auto call1 = id(lamp_leds).toggle();
          auto call2 = id(lamp_uplight_leds).toggle();
          call1.perform();
          call2.perform();
        }

binary_sensor:
  # - platform: remote_receiver
  #   id: led_remote_power
  #   nec:
  #     address: 0x00FF
  #     command: 0xBF40
  #   on_press:
  #     then:
  #       - light.toggle: lamp_leds
  #       - light.toggle: lamp_uplight_leds
  #       - light.toggle: left_leds
  #       - light.toggle: right_leds
  - platform: gpio
    id: leds_off_button
    pin:
      number: 0
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 500ms
      then:
        - light.turn_off:
            id: lamp_leds
        - light.turn_off:
            id: lamp_uplight_leds
  # - platform: gpio
  #   id: lamp_leds_on_button
  #   pin:
  #     number: 35
  #     inverted: true
  #   on_click:
  #     min_length: 50ms
  #     max_length: 500ms
  #     then:
  #       - light.turn_on:
  #           id: lamp_leds
  #           brightness: 1.0
  #           red: 1.0
  #           green: 0.933
  #           blue: 0.753
  #           white: 1.0
  # - platform: gpio
  #   id: lamp_uplight_leds_on_button
  #   pin:
  #     number: 34
  #     inverted: true
  #   on_click:
  #     min_length: 50ms
  #     max_length: 500ms
  #     then:
  #       - light.turn_on:
  #           id: lamp_uplight_leds
  #           brightness: 1.0
  #           red: 1.0
  #           green: 0.933
  #           blue: 0.753
  #           white: 1.0

light:
  - platform: rgbw
    id: lamp_leds
    name: Head
    restore_mode: RESTORE_DEFAULT_OFF
    red: lamp_pwm_red_channel
    green: lamp_pwm_green_channel
    blue: lamp_pwm_blue_channel
    white: lamp_pwm_white_channel
    effects:
      - random:
      - strobe:
      - flicker:
  - platform: rgbw
    id: lamp_uplight_leds
    name: Uplight
    restore_mode: RESTORE_DEFAULT_OFF
    red: lamp_uplight_pwm_red_channel
    green: lamp_uplight_pwm_green_channel
    blue: lamp_uplight_pwm_blue_channel
    white: lamp_uplight_pwm_white_channel
    effects:
      - random:
      - strobe:
      - flicker:

output:
  - platform: ledc
    id: lamp_pwm_red_channel
    pin: 16
  - platform: ledc
    id: lamp_pwm_green_channel
    pin: 18
  - platform: ledc
    id: lamp_pwm_blue_channel
    pin: 13
  - platform: ledc
    id: lamp_pwm_white_channel
    pin: 27
  - platform: ledc
    id: lamp_uplight_pwm_red_channel
    pin: 15
  - platform: ledc
    id: lamp_uplight_pwm_green_channel
    pin: 17
  - platform: ledc
    id: lamp_uplight_pwm_blue_channel
    pin: 12
  - platform: ledc
    id: lamp_uplight_pwm_white_channel
    pin: 14