substitutions:
  node_name: esp-lights-string-patio-south
  node_friendly_name: String Lights Patio South

packages:
  esp_common: !include shared/esp__common_core.yaml
  esp_lights_string_base: !include shared/esp-lights-string-base.yaml
