substitutions:
  node_name: esp-lights-bathroom
  node_friendly_name: Bathroom Vanity
  project_name: kbxLEDController-16ch
  project_version: v2

packages:
  esp_common: !include shared/esp__common_core.yaml

wifi:
  enable_btm: true
  enable_rrm: true
  output_power: 14dB  # prevent brownouts

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

script:
  - id: downlight_auto_on
    mode: restart
    then:
      - light.turn_on:
          id: bathroom_vanity_downlight
          brightness: !lambda "return id(auto_on_target_brightness).state;"
          red: !lambda "return id(auto_on_target_red).state;"
          green: !lambda "return id(auto_on_target_green).state;"
          blue: !lambda "return id(auto_on_target_blue).state;"
          white: !lambda "return id(auto_on_target_white).state;"
  - id: uplight_auto_on
    mode: restart
    then:
      - light.turn_on:
          id: bathroom_vanity_uplight
          brightness: !lambda "return id(auto_on_target_brightness).state;"
          red: !lambda "return id(auto_on_target_red).state;"
          green: !lambda "return id(auto_on_target_green).state;"
          blue: !lambda "return id(auto_on_target_blue).state;"
          white: !lambda "return id(auto_on_target_white).state;"

status_led:
  pin:
    number: 5
    inverted: true

uart:
  id: ld2420_uart
  rx_pin: 4
  tx_pin: 2
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

ld2420:

text_sensor:
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware

sensor:
  - platform: ld2420
    moving_distance:
      name: Moving Distance

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode
  # template selects to control motion activation behavior of lights
  - platform: template
    id: bathroom_vanity_motion_activation_lower
    name: Motion Activation Lower
    entity_category: config
    optimistic: true
    options:
      - Enabled
      - Turn Off Only
      - Disabled
    initial_option: Enabled
    restore_value: true
  - platform: template
    id: bathroom_vanity_motion_activation_upper
    name: Motion Activation Upper
    entity_category: config
    optimistic: true
    options:
      - Enabled
      - Turn Off Only
      - Disabled
    initial_option: Enabled
    restore_value: true

number:
  - platform: template
    id: auto_on_target_brightness
    name: Auto-On Target Brightness
    entity_category: config
    mode: box
    optimistic: true
    min_value: 0
    max_value: 1
    step: 0.001
    initial_value: 1.0
    restore_value: true
  - platform: template
    id: auto_on_target_red
    name: Auto-On Target Red
    entity_category: config
    mode: box
    optimistic: true
    min_value: 0
    max_value: 1
    step: 0.001
    initial_value: 1.0
    restore_value: true
  - platform: template
    id: auto_on_target_green
    name: Auto-On Target Green
    entity_category: config
    mode: box
    optimistic: true
    min_value: 0
    max_value: 1
    step: 0.001
    initial_value: 0.77
    restore_value: true
  - platform: template
    id: auto_on_target_blue
    name: Auto-On Target Blue
    entity_category: config
    mode: box
    optimistic: true
    min_value: 0
    max_value: 1
    step: 0.001
    initial_value: 0.048
    restore_value: true
  - platform: template
    id: auto_on_target_white
    name: Auto-On Target White
    entity_category: config
    mode: box
    optimistic: true
    min_value: 0
    max_value: 1
    step: 0.001
    initial_value: 1.0
    restore_value: true
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum
    gate_move_sensitivity:
      name: Move Calibration Sensitivity Factor
    gate_still_sensitivity:
      name: Still Calibration Sensitivity Factor
    gate_0:
      move_threshold:
        name: Gate 0 Move Threshold
      still_threshold:
        name: Gate 0 Still Threshold
    gate_1:
      move_threshold:
        name: Gate 1 Move Threshold
      still_threshold:
        name: Gate 1 Still Threshold
    gate_2:
      move_threshold:
        name: Gate 2 Move Threshold
      still_threshold:
        name: Gate 2 Still Threshold
    gate_3:
      move_threshold:
        name: Gate 3 Move Threshold
      still_threshold:
        name: Gate 3 Still Threshold
    gate_4:
      move_threshold:
        name: Gate 4 Move Threshold
      still_threshold:
        name: Gate 4 Still Threshold
    gate_5:
      move_threshold:
        name: Gate 5 Move Threshold
      still_threshold:
        name: Gate 5 Still Threshold
    gate_6:
      move_threshold:
        name: Gate 6 Move Threshold
      still_threshold:
        name: Gate 6 Still Threshold
    gate_7:
      move_threshold:
        name: Gate 7 Move Threshold
      still_threshold:
        name: Gate 7 Still Threshold
    gate_8:
      move_threshold:
        name: Gate 8 Move Threshold
      still_threshold:
        name: Gate 8 Still Threshold
    gate_9:
      move_threshold:
        name: Gate 9 Move Threshold
      still_threshold:
        name: Gate 9 Still Threshold
    gate_10:
      move_threshold:
        name: Gate 10 Move Threshold
      still_threshold:
        name: Gate 10 Still Threshold
    gate_11:
      move_threshold:
        name: Gate 11 Move Threshold
      still_threshold:
        name: Gate 11 Still Threshold
    gate_12:
      move_threshold:
        name: Gate 12 Move Threshold
      still_threshold:
        name: Gate 12 Still Threshold
    gate_13:
      move_threshold:
        name: Gate 13 Move Threshold
      still_threshold:
        name: Gate 13 Still Threshold
    gate_14:
      move_threshold:
        name: Gate 14 Move Threshold
      still_threshold:
        name: Gate 14 Still Threshold
    gate_15:
      move_threshold:
        name: Gate 15 Move Threshold
      still_threshold:
        name: Gate 15 Still Threshold

button:
  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits

binary_sensor:
  # API status sensor
  - platform: status
    id: bathroom_vanity_api_status
    name: API Status
    internal: true
  # motion sensor (via sensor nodule)
  - platform: ld2420
    has_target:
      id: bathroom_vanity_motion_detection
      name: Presence
      on_press:
        then:
          # only switch the light based on the mode defined by the template select
          - if:
              condition:
                lambda: |-
                  return id(bathroom_vanity_motion_activation_lower).state == "Enabled" || !id(bathroom_vanity_api_status).state;
              then:
                - script.execute: downlight_auto_on
          # only switch the light based on the mode defined by the template select
          - if:
              condition:
                lambda: |-
                  return id(bathroom_vanity_motion_activation_upper).state == "Enabled" || !id(bathroom_vanity_api_status).state;
              then:
                - script.execute: uplight_auto_on
      on_release:
        then:
          # only switch the light based on the mode defined by the template select
          - if:
              condition:
                lambda: |-
                  return id(bathroom_vanity_motion_activation_lower).state != "Disabled" || !id(bathroom_vanity_api_status).state;
              then:
                - light.turn_off: bathroom_vanity_downlight
          # only switch the light based on the mode defined by the template select
          - if:
              condition:
                lambda: |-
                  return id(bathroom_vanity_motion_activation_upper).state != "Disabled" || !id(bathroom_vanity_api_status).state;
              then:
                - light.turn_off: bathroom_vanity_uplight
  # sensors for buttons for manual control of lights
  - platform: gpio
    id: bathroom_lights_off_button
    pin:
      number: 0
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 500ms
      then:
        - light.turn_off:
            id: bathroom_vanity_uplight
        - light.turn_off:
            id: bathroom_vanity_downlight
  - platform: gpio
    id: bathroom_vanity_uplight_on_button
    pin:
      number: 34
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 500ms
      then:
        - script.execute: uplight_auto_on
  - platform: gpio
    id: bathroom_vanity_downlight_on_button
    pin:
      number: 35
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 500ms
      then:
        - script.execute: downlight_auto_on

light:
  - platform: rgbw
    id: bathroom_vanity_downlight
    name: Downlight
    restore_mode: RESTORE_DEFAULT_OFF
    red: bathroom_vanity_downlight_pwm_red_channel
    green: bathroom_vanity_downlight_pwm_green_channel
    blue: bathroom_vanity_downlight_pwm_blue_channel
    white: bathroom_vanity_downlight_pwm_white_channel
    effects:
      - random:
      - strobe:
      - flicker:
  - platform: rgbw
    id: bathroom_vanity_uplight
    name: Uplight
    restore_mode: RESTORE_DEFAULT_OFF
    red: bathroom_vanity_uplight_pwm_red_channel
    green: bathroom_vanity_uplight_pwm_green_channel
    blue: bathroom_vanity_uplight_pwm_blue_channel
    white: bathroom_vanity_uplight_pwm_white_channel
    effects:
      - random:
      - strobe:
      - flicker:

output:
  - platform: ledc
    id: bathroom_vanity_downlight_pwm_red_channel
    pin: 16
  - platform: ledc
    id: bathroom_vanity_downlight_pwm_green_channel
    pin: 18
  - platform: ledc
    id: bathroom_vanity_downlight_pwm_blue_channel
    pin: 13
  - platform: ledc
    id: bathroom_vanity_downlight_pwm_white_channel
    pin: 27
  - platform: ledc
    id: bathroom_vanity_uplight_pwm_red_channel
    pin: 25
  - platform: ledc
    id: bathroom_vanity_uplight_pwm_green_channel
    pin: 26
  - platform: ledc
    id: bathroom_vanity_uplight_pwm_blue_channel
    pin: 33
  - platform: ledc
    id: bathroom_vanity_uplight_pwm_white_channel
    pin: 32
