substitutions:
  node_name: esp-sensor-dry-box
  node_friendly_name: "Dry Box"

packages:
  esp_common: !include shared/esp__common_core.yaml

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: 5.0.2
    platform_version: 6.3.2

i2c:
  id: i2c_bus
  frequency: 400kHz
  sda: 2
  scl: 9

sensor:
  - platform: bme280
    address: 0x76
    temperature:
      id: bme280_temperature
      name: BME280 Temperature
      filters:
        - offset: -0.5
    humidity:
      id: bme280_humidity
      name: BME280 Humidity
    pressure:
      id: bme280_pressure
      name: BME280 Pressure
    update_interval: 15s
  - platform: shtcx
    temperature:
      id: shtcx_temperature
      name: SHTC3 Temperature
      filters:
        - offset: -1
    humidity:
      id: shtcx_humidity
      name: SHTC3 Humidity
    update_interval: 15s
  # - platform: dht
  #   pin: 2
  #   model: DHT22
  #   temperature:
  #     name: Temperature
  #   humidity:
  #     name: Humidity
  #   update_interval: 15s