substitutions:
  node_name: esp-lights-neon-palm-tree
  node_friendly_name: "Neon Palm Tree"
  dac_min_power: "0.15"
  dac_max_power: "0.95"

packages:
  esp_common: !include shared/esp__common_core.yaml
  esp_lights_neon_base: !include shared/esp-lights-neon-base-v2.yaml