substitutions:
  node_name: esp-lights-neon-edison-bulb
  node_friendly_name: "Neon Edison Bulb"
  dac_min_power: "0.10"
  dac_max_power: "1.0"

packages:
  esp_common: !include shared/esp__common_core.yaml
  esp_lights_neon_base: !include shared/esp-lights-neon-base-v3.yaml
