substitutions:
  node_name: esp-3ch-psu-controller
  node_friendly_name: 3 Channel PSU
  project_name: 3chPSU
  project_version: v1

packages:
  esp_common: !include shared/esp__common_core.yaml

wifi:
  enable_btm: true
  enable_rrm: true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

logger:
  hardware_uart: UART0

status_led:
  pin:
    number: 9
    inverted: true

switch:
  - platform: gpio
    pin: 21
    name: Channel 1
    id: channel_1
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    pin: 2
    name: Channel 2
    id: channel_2
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    pin: 20
    name: Channel 3
    id: channel_3
    restore_mode: RESTORE_DEFAULT_ON